title: [Le Bestiaire Des Chats]
description: [Une encyclopédie indispensable faite par Anthony]
url: "https://anthonyjnd.github.io"     # ton domaine GitHub Pages
baseurl: "/Bestiaire"                   # nom de ton dépôt
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
include:
  - _includes
